### ISSUE TITLE
Original repo missing

### ISSUE THREAD

**Issue by nertzy** [nertzy/pg_search#1]
The repo at https://github.com/Casecommons/pg_search is missing! It appears that the @Casecommons organization owners either deleted it or made it private without consulting me. It's been several years since I've worked with them so I'm assuming that this is all a big misunderstanding and miscommunication.

I'm doing what I can to recover whatever I have under my control. I've also reached out to the organization owners to see if they still have the repo and can recover what's missing.

For now, I have all the source code for the master branch and all tags from released versions available here. Unfortunately I don't have any copies of:
- issues
- pull requests
- wiki pages

I'm hoping for the best. Wish us luck!

Grant Hutchins

**Comment by CCTristan** [comment]
This was taken private as part of a security sweep on our account. We are doing a review of the repository and should have a resolution soon.

**Comment by chevinbrown** [comment]
I just got a @dependabot version bump, but can't see changes, which _also seems like a security concern_.

**Comment by nertzy** [comment]
@chevinbrown Here is the diff: https://github.com/nertzy/pg_search/compare/v2.1.5...v2.1.6

The original repo is now back up and so you can compare that to https://github.com/Casecommons/pg_search/compare/v2.1.5...v2.1.6 as well.

You can inspect the Git SHAs and see that the history is the same and is consistent between the two repos and the published gem.

I'll post an update here once we figure out the long term plan.

**Comment by nertzy** [comment]
I went ahead and pushed version 2.1.7 which points back to the original repo location.

https://github.com/Casecommons/pg_search

**Comment by aried3r** [comment]
Hey! If SHAs match, could we maybe have a post-incident report on why this was done, @CCTristan? 

Cheers!

**Comment by CCTristan** [comment]
@aried3r This was caught into a sweep of repositories by mistake during a round of security tightening for all our other repositories. Apologies on this.
